{% set name = "sphinx-immaterial" %}
{% set dunder_name = name.replace("-", "_") %}
{% set version = "0.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ dunder_name }}/{{ dunder_name }}-{{ version }}.tar.gz
  sha256: 0c06f2b18dffc8a3ae04ce9e7f1d4a011dd4811965558a6b394484b9af2f3ec4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<4
    - nodejs >=16
  run:
    - python >=3.8,<4
    - sphinx >=4.5
    - markupsafe
    - pydantic >=2.4
    - pydantic-extra-types
    - typing-extensions
    - appdirs
    - requests

test:
  imports:
    - sphinx_immaterial

about:
  home: https://github.com/jbms/sphinx-immaterial
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sphinx-Immaterial Theme
  doc_url: https://sphinx-immaterial.readthedocs.io/
  dev_url: https://github.com/jbms/sphinx-immaterial

extra:
  recipe-maintainers:
    - sdebionne
