schema_version: 1

context:
  name: sphinx-immaterial
  dunder_name: ${{ name | replace("-", "_") }}
  version: 0.12.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ dunder_name }}/${{ dunder_name }}-${{ version }}.tar.gz
  sha256: a7c0c4be3dcb4960eb7b299dfee07cdf8a02bf56821f5d0d62e5d31b7b7b5ec5

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python ${{ python_min }}.*
    - nodejs >=16
  run:
    - python >=${{ python_min }},<4
    - sphinx >=4.5
    - markupsafe
    - pydantic >=2.4
    - pydantic-extra-types
    - typing-extensions
    - appdirs
    - requests

tests:
  - python:
      imports:
        - sphinx_immaterial
      python_version: ${{ python_min }}.*
about:
  license: MIT
  license_file: LICENSE
  summary: Sphinx-Immaterial Theme
  homepage: https://github.com/jbms/sphinx-immaterial
  repository: https://github.com/jbms/sphinx-immaterial
  documentation: https://sphinx-immaterial.readthedocs.io/

extra:
  recipe-maintainers:
    - sdebionne
